apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "share-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
