apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "share-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
